### ISSUE TITLE
Undocumented deleting key of SET after removing last member

### ISSUE THREAD

**Issue by nolimitdev** [antirez/redis-doc#1066]
I have checked DOC for commands [smembers](https://redis.io/commands/smembers) [srem](https://redis.io/commands/srem) and also DOC for [SETS](https://redis.io/topics/data-types#sets) and there is not information that SET can not be empty, so after removing last member entire key is deleted. Why users have to learn this behavior from 3rd party websites/blogs such as https://www.bennadel.com/blog/2965-redis-doesn-t-store-empty-sets-or-hashes-and-will-delete-empty-sets-and-hashes.htm

Could you please update DOC? Thanks!

**Comment by itamarhaber** [comment]
Hello @nolimitdev 

You are correct that this behavior is not mentioned in the commands' documentation. In fact, all of Redis' aggregate data types excluding the Stream, are removed automatically when they are "empty". This is documented at https://redis.io/topics/data-types-intro#automatic-creation-and-removal-of-keys:

> 2. When we remove elements from an aggregate data type, if the value remains empty, the key is automatically destroyed.

So, potentially, users could read that and learn about this behavior. On the other hand, the docs for various commands (e.g. `SREM` and `SPOP` for Sets, `HDEL` for Hashes, all List pop operations, and so forth) could be added with that note. If you feel this is needed, you can make a PR to that effect, but personally I feel this is somewhat of an overkill.

**Comment by nolimitdev** [comment]
Thank you for your detailed explanation.

**Comment by KazankovMarch** [comment]
I don't see this in docs:
> When we remove elements from an aggregate data type, if the value remains empty, the key is automatically destroyed.

Please let's add this info 🙏 

It is very important: we need to know if we need to clean up empty hashes/sets ourself or not. I want to rely on Redis to avoid excess manual deletion, but as it is not officially documented, I does not look like a feature you can rely on
