### ISSUE TITLE
EXPIRE on existing key does not work as described

### ISSUE THREAD

**Issue by hikeonpast** [antirez/redis-doc#107]
http://www.redis.io/topics/expire

"Trying to call EXPIRE against a key that already has an associated timeout will not change the timeout of the key, but will just return 0."

Unfortunately, it turns out that this statement is incorrect--EXPIRE on an existing key replaces the prior TTL with the TTL argument from the EXPIRE command.

Redis 2.4.8:

redis db2:6381[2]> setex test 20 asdf
OK
redis db2:6381[2]> ttl test
(integer) 19
redis db2:6381[2]> expire test 60
(integer) 1
redis db2:6381[2]> ttl test
(integer) 59

**Comment by badboy** [comment]
Does not apply anymore.
