### ISSUE TITLE
Typo error "losign" chould be changed to "losing". 

### ISSUE THREAD

**Issue by jacobliuat** [antirez/redis-doc#1107]
https://redis.io/topics/replication

 However with WAIT the probability of losign a write after a failure event is greatly reduced to certain hard to trigger failure modes.

==>  Typo error "losign" chould be changed to "losing". 

 However with WAIT the probability of losing a write after a failure event is greatly reduced to certain hard to trigger failure modes.

**Comment by itamarhaber** [comment]
Hello @jacobliuat 

Thanks for spotting the typo. You can submit a PR that fixes this issue if you want.

**Comment by PansonPanson** [comment]
fixed it

**Comment by itamarhaber** [comment]
Fixed by #1158 (blame: @charsyam ;P)
