### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by limithit** [antirez/redis-doc#1114]
Hi, I am a redis module developer. I am writing a book. One of the chapters covers the official documentation. Can I translate it into Chinese and let more people touch the module development?

**Comment by itamarhaber** [comment]
Hello @limithit 

The documentation's license is Creative Commons Attribution-ShareAlike 4.0 International - I believe it allows you to do that.

Are you familiar with the Chinese translation at http://redis.cn?

**Comment by limithit** [comment]
Of course thank you @itamarhaber
