### ISSUE TITLE
[Redis] Does redis support the secondary index on String data type?

### ISSUE THREAD

**Issue by shikhil-gupta** [antirez/redis-doc#1123]
I would like to know does redis provide support of secondary index on String data type?

**Comment by itamarhaber** [comment]
Hello @shikhil-gupta 

Redis provides the tools to build indices, but does not perform indexing of data implicitly - you'd have to implement the logic in your code. For more information about indexing patterns in Redis please refer to https://redis.io/topics/indexes.

Keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the Redis documentation. Questions should be directed to the [community](https://redis.io/community):

* [/r/redis subreddit](http://www.reddit.com/r/redis)
* [the mailing list](https://groups.google.com/forum/#!forum/redis-db)
* [the `redis` tag at StackOverflow](http://stackoverflow.com/questions/tagged/redis)
* [the irc channel #redis](http://webchat.freenode.net/?channels=redis) on freenode.
