### ISSUE TITLE
"^" is being read as pow() rather than as string

### ISSUE THREAD

**Issue by ashtul** [antirez/redis-doc#1129]
On ./topics/modules-api-ref.md for function RedisModule_DictIteratorStartC when reading thought https://redis.io/topics/modules-api-ref, "^" is interperted as "<sup>"</sup> (second one as superscript).

**Comment by itamarhaber** [comment]
Hello @ashtul 

FYI, the api's docs are auto-generated from the comments in the source code via a Ruby script. The fix should be applied there.

**Comment by ashtul** [comment]
Olah @itamarhaber 
Who should I notify of this?
