### ISSUE TITLE
Minor grammar issues.

### ISSUE THREAD

**Issue by adjenks** [antirez/redis-doc#1150]
### /topics/persistence:
> It is possible that the server crashed while writing the AOF file, or that the volume where the AOF file is stored is store was full.

### /topics/memory-optimization:
> However allocators are smart and are able to reuse free chunks of memory, so after you freed 2GB of your 5GB data set, when you start adding more keys again, you'll see the RSS (Resident Set Size) to stay steady and don't grow more, as you add up to 2GB of additional keys.

**Comment by itamarhaber** [comment]
Hello @adjenks 

Thanks for opening this issue. It would be helpful if you could submit a PR to fix mistakes, in case they have not been addressed yet.

**Comment by adjenks** [comment]
Fixed by https://github.com/antirez/redis-doc/pull/1201

**Comment by itamarhaber** [comment]
👍
