### ISSUE TITLE
update lpushx rpushx doc for variable elements support 

### ISSUE THREAD

**Issue by patpatbear** [antirez/redis-doc#1154]
`LPUSHX` and `RPUSHX` accepts varaible number of elements since Redis 4.0.0-RC1,
but it seems like that this feature was never documented, hence the redis-cli hint
also does not imply `LPUSHX` and `RPUSHX`  support varaible elements.

release note for 4.0.0:

```
================================================================================
Redis 4.0.0-RC1   Released Fri Dec 2 10:40:01 CEST 2016
================================================================================
...
* RPUSHX and LPUSHX now accept a variable number of elements.
...
```

**Comment by itamarhaber** [comment]
Thanks @patpatbear - #1155 has been merged so closing.
