### ISSUE TITLE
New arguments on exisiting commands don't have "Since"

### ISSUE THREAD

**Issue by gkorland** [antirez/redis-doc#1166]
e.g.
[Scan](https://redis.io/commands/scan) has a new optional argument called `TYPE` but there is no way to know from the documentation that it was only added at Redis 6.x

**Comment by itamarhaber** [comment]
Hello @gkorland 

Thanks for pointing this out. I've created #1196 to address this specific issue. Please feel free to open new issues if you find additional documentation omissions such as this one.
