### ISSUE TITLE
Missing word in Sentinel Quick Start guide

### ISSUE THREAD

**Issue by mfoo** [antirez/redis-doc#1209]
See https://redis.io/topics/sentinel#quick-start.

> It is a rewrite of the initial Sentinel implementation using stronger and simpler to predict algorithms (that are explained in this documentation).

A word is missing after "simpler", but I'm not sure what it should be.

**Comment by itamarhaber** [comment]
Hello @mfoo 

I can see how the wording is confusing, but I don't think there are any missing words, but possibly a couple of hyphens:

> It is a rewrite of the initial Sentinel implementation using stronger and simpler-to-predict algorithms (that are explained in this documentation).

What do you think?

**Comment by mfoo** [comment]
Ah! I totally hadn't read it like that. I though it was trying to say something like "using stronger and simpler algorithms to predict..."

Yes, that would be better (for me), thanks!
