### ISSUE TITLE
GEORADIUS doesn't seem to be documented correctly?

### ISSUE THREAD

**Issue by ioquatix** [antirez/redis-doc#1227]
In the JSON commands it has an argument order and not count, but on the HTML documentation it has count, but not order. Not sure what is correct. Just FYI.

**Comment by itamarhaber** [comment]
Hello @ioquatix and thanks. I do not see the issue, but perhaps an explanation would help.

Redis commands arguments generally fall into one of three categories:
1. Positional - i.e. the first argument, often the key name
2. Subcommand - arguments that are one word subcommands, such as `ASC` and `DESC` describing the "order"
3. Subcommand and its argument - arguments that require a subcommand before them, such as `COUNT count` where "COUNT" is the subscommand and "count" is the argument.

In this case, `GEORADIUS` uses all types. The command is defined correctly in the JSON and rendered correctly in the HTML in my opinion.

**Comment by ioquatix** [comment]
My bad, my script processing `command.json` was skipping some arguments so I thought it was missing from the source file... you are correct. Thanks for the quick response.
