### ISSUE TITLE
lua redia admin,redis client tool,redis web client,redis web ui,openresty lor lua support

### ISSUE THREAD

**Issue by lifeblood** [antirez/redis-doc#1242]
hi, antirez
lua redia admin,Redis client tool, Redis web client, Redis web UI, openresty  lor Lua support(https://github.com/lifeblood/lua-redis-admin)

Can  add your homepage at https://redis.io/clients ?

Thank you in advance

**Comment by itamarhaber** [comment]
Hello @lifeblood 

In order to add your tool to the list you only need to submit PR with the details to https://github.com/antirez/redis-doc/blob/master/tools.json

**Comment by lifeblood** [comment]
Ok, I have submitted, please check
