### ISSUE TITLE
Client kill formatting problem

### ISSUE THREAD

**Issue by ersoy-insider** [antirez/redis-doc#1313]
This commit https://github.com/antirez/redis-doc/commit/e49a6dec3f2573342613d5fb20e3790c2cf80358  causes this formatting in `client-kill` page.

![image](https://user-images.githubusercontent.com/17027410/82739713-8a339b00-9d4a-11ea-92a5-1cc6ed8f1093.png)

Best

**Comment by itamarhaber** [comment]
Thanks @ersoy-insider - fixing.
