### ISSUE TITLE
XTRIM doc issue for MINID argument

### ISSUE THREAD

**Issue by elirag** [antirez/redis-doc#1875]
Should be: "MINID: the oldest ID in the stream will be exactly the **maximum** between its original oldest ID and the specified threshold."

**Comment by enjoy-binbin** [comment]
https://redis.io/commands/xtrim/
look like you are right, can you make a PR to fix it?

**Comment by elirag** [comment]
there you go https://github.com/redis/redis-doc/pull/1878
