### ISSUE TITLE
Redis common patterns section

### ISSUE THREAD

**Issue by luca3m** [antirez/redis-doc#273]
Hi,

I use a lot Redis and I think that it's for DBs what RISC it's of CPUs. A set of simple functions that you can use to build your own, to extend it and have a database that matches your needs.

So using redis I noticed common patterns like implementing message queues using an array with blocking pop and a "working" set. Or using a sorted set to implement a scheduler using timestamp as score.

What do you think about adding on documentation/website a section with these patterns? I think that can be useful for people to understand better how to use redis or to extend them avoiding common mistakes.

**Comment by itamarhaber** [comment]
Hello @luca3m 

That's a great idea. In fact, some of the documentation already contains use patterns - if you have any additional suggestions for such patterns, please feel free to add them via PRs.
