### ISSUE TITLE
Number of keys sampled per expire loop is wrong

### ISSUE THREAD

**Issue by larryng** [antirez/redis-doc#461]
In commands/expire.md:

> Specifically this is what Redis does 10 times per second:
> 1. Test 100 random keys from the set of keys with an associated expire.
> ...

Also, in the "Latency generated by expires" section of topics/latency.md:

> Given that `REDIS_EXPIRELOOKUPS_PER_CRON` is set to 10 by default, and the process is performed ten times per second, usually just 100 keys per second are actively expired.

From what I can tell from reading the Redis source, the actual number is set in `ACTIVE_EXPIRE_CYCLE_LOOKUPS_PER_LOOP` which is [to 20 in the latest stable](https://github.com/antirez/redis/blob/2.8/src/redis.h#L136).

**Comment by badboy** [comment]
Fixed by #462
