### ISSUE TITLE
Clarify which events cause EXPIRE timeout to be cleared

### ISSUE THREAD

**Issue by t-mw** [antirez/redis-doc#643]
Currently the docs for [EXPIRE](https://github.com/antirez/redis-doc/blob/master/commands/expire.md) state:

> The timeout is cleared only when the key is removed using the DEL command or overwritten using the SET or GETSET commands.

This is misleading, because other commands including the `*STORE` commands (`SINTERSTORE`, `SUNIONSTORE`, `SDIFFSTORE`, `ZUNIONSTORE` and `ZINTERSTORE`) also clear the timeout, not _only_ `DEL`, `SET` and `GETSET`. Those additional commands should either be listed, or the wording of the sentence should be changed to imply that other commands can also clear the timeout.

Correct me if I'm wrong, but commands which clear the timeout appear to be ones which raise `del` and `set` events (listed [here](http://redis.io/topics/notifications#events-generated-by-different-commands)). In that case, the following might be a better explanation:

> The timeout is cleared only when a `del` or `set` event is raised for the key. Commands which raise those events include `DEL`, `SET` and `GETSET`, as well as commands which overwrite an existing value.

Happy to create a PR once I'm certain that the event explanation is correct.

**Comment by badboy** [comment]
Good finding. I'd appreciate a PR, the changes look good to me.

**Comment by antirez** [comment]
I like the idea of changing it, but expressing EXPIRE semantics in terms of a complex feature like events is not a good idea for newcomers. It's probably better to just say, every command that deletes or overwrites the content of a key, such as DEL, SET, GETSET and all the *STORE commands, will reset the EXPIRE value. It's a lot more accessible for newcomers.

**Comment by t-mw** [comment]
I agree, I've suggested a change without involving events: #644
