### ISSUE TITLE
documentation page - broken link

### ISSUE THREAD

**Issue by ambrozic** [antirez/redis-doc#651]
On documentation page (http://redis.io/documentation), link to **Debugging Lua scripts** points to http://redis.io/commands/ldb but it should point to http://redis.io/topics/ldb.

I would create pull request but i cant find this bit in repository.

I apologise if i am missing something.

Cheers

**Comment by itamarhaber** [comment]
Wrong repo (although it is confusing, true) - please close this and reopen at: https://github.com/antirez/redis-io/blob/master/views/documentation.md

**Comment by ambrozic** [comment]
thanks @itamarhaber
