### ISSUE TITLE
unknown command 'ZRANGEBYLEX'

### ISSUE THREAD

**Issue by ramwin1** [antirez/redis-doc#659]
The <a href="http://redis.io/topics/data-types-intro#lexicographical-scores">documents</a> said the zrangebylex has been added into Redis since 2.8. But when I type into the command <b>"zrangebylex hackers [B [P"</b>, it caused an error. Is this command removed in the latest version? Thank you for your reading.

I'm using Ubuntu 14.04, the Redis version is 3.0.6. 
I ran <b>"apt-get install redis-server"</b> to install the redis.

**Comment by ramwin1** [comment]
I met the same problem when I use the BITPOS command

**Comment by itamarhaber** [comment]
v3.0.6 supports both ZRANGEBYLEX (v2.8.9) and BITPOS (v2.8.7).

When I do `apt-get install redis-server` on Ubuntu 14.04 I get Redis v2.8.4
(verifiable via `redis-cli INFO server`) - are you sure that you're running
3.0.6?

I met the same problem when I use the BITPOS command

—
Reply to this email directly or view it on GitHub
<https://github.com/antirez/redis-doc/issues/659#issuecomment-170545773>.

**Comment by ramwin1** [comment]
I'm little confused. 
<img src="https://raw.githubusercontent.com/ramwin1/netdisk/master/redisversion.png"/>
The infomation of redis show that the version of redis is 3.0.6, when I type in the <strong>zrange</strong> and press tab key, it auto complete the <strong>zrangebylex</strong>.
But when I use dpkg command to see the version of redis, it shows the version is 2.8.4
I try to use the <a href="http://www.redis.io/download#installation">installation guide</a> to install the redis, but I still get this problem.
<img src="https://raw.githubusercontent.com/ramwin1/netdisk/master/redisversion2.png"/>

**Comment by ramwin1** [comment]
It seems that there is two redis-server on my computer. One is installed by ubuntu and another is in the ~/Downloads/redis-3.0.6/src/redis-server.
After I removed the redis-server of ubuntu, and run the server by ~/Downloads/redis-3.0.6/src/redis-server, then I can use the command zrangebylex.
Again, thank you for your reading and response.

**Comment by itamarhaber** [comment]
I'm happy you solved your issue, just  note that the version reported by
redis-cli isn't that of the server's, but of the CLI itself.
