### ISSUE TITLE
wondering some typos in persistence documentation

### ISSUE THREAD

**Issue by kunth** [antirez/redis-doc#660]
Formerly I post this here, [https://github.com/antirez/redis/issues/2997](https://github.com/antirez/redis/issues/2997), but not the right place, so I come here to ask this question.

When I read the [persistence documentations](http://redis.io/topics/persistence), in the Chapter of "AOF disadvantages", I find the sentences as follows:

>However - 1) It should be noted that every time the **AOF** is rewritten by Redis it is recreated from scratch starting from the actual data contained in the data set, making resistance to bugs stronger compared to an always appending AOF file (or one rewritten reading the old AOF instead of reading the data in memory). 2) We never had a single report from users about an **AOF** corruption that was detected in the real world.

I am wondering that the two leading AOFs in both sentences are RDBs? That means, I think it should be

>However - 1) It should be noted that every time the **RDB** is rewritten by Redis it is recreated from scratch starting from the actual data contained in the data set, making resistance to bugs stronger compared to an always appending AOF file (or one rewritten reading the old AOF instead of reading the data in memory). 2) We never had a single report from users about an **RDB** corruption that was detected in the real world.

**Comment by badboy** [comment]
Nope, it's talking about the AOF rewriting, which takes the current dataset and turns that into the right commands that are then written to a new AOF file. 
So if before the rewrite it would contain `SET foo value-1; DEL foo; SET foo value-2`, after the rewrite it will only contain `SET foo value-2` as this is enough to reconstruct the current dataset.
