### ISSUE TITLE
Confusing use of the term "pure function"

### ISSUE THREAD

**Issue by marfire** [antirez/redis-doc#693]
The [`EVAL`](https://github.com/antirez/redis-doc/blob/dab803f3842a8b9cafde4a2fbccc7b79ebe67c17/commands/eval.md) scripting documentation refers to scripts as *pure functions* in a few places (e.g. "A very important part of scripting is writing scripts that are pure functions").

However, the term "pure function" has a specific meaning in programming (see, for example, [Wikipedia](https://en.wikipedia.org/wiki/Pure_function)): they are functions whose return value is entirely determined by their arguments, and which don't have side effects.

Redis scripts are not that. They do have side effects (modifications to the database), and the return value can be random as long as the database writes are deterministic.

The rest of the documentation is pretty clear on this point (the key line is "The script must always evaluates [sic] the same Redis write commands with the same arguments given the same input data set"), so I would just avoid using the term *pure function*. "Scripts with deterministic side effects" doesn't have quite the same ring to it as "Scripts as pure functions", perhaps, but it would be more accurate.

**Comment by itamarhaber** [comment]
Sounds good - PR it?

**Comment by marfire** [comment]
OK. I cleaned up some other parts of the replication section as well.

**Comment by badboy** [comment]
Overtaken by PR. Will read that later.

**Comment by marfire** [comment]
Since the problem has not been fixed, the issue should be re-opened.

**Comment by badboy** [comment]
Hm, wasn't this submitted as a PR? If not, can you do so?

**Comment by marfire** [comment]
It's still there: #695.
