### ISSUE TITLE
topics/signals.md refers to old version

### ISSUE THREAD

**Issue by ecksun** [antirez/redis-doc#759]
https://github.com/antirez/redis-doc/blob/255066049787697361f10add56d53d2f546e5787/topics/signals.md states:

    * Since Redis 2.8 (currently a development version) a fast memory test is performed as a first check of the reliability of the crashing system.

Since redis 3.2.4 is the latest stable version 2.8 is obviously not the development version. I do not know the current behavior so I cannot create a PR to fix this.

**Comment by badboy** [comment]
Closed by https://github.com/antirez/redis-doc/commit/a8f5c57622fc39d9f8bc3b4349924422b1826d10
