### ISSUE TITLE
OBJECT documentation

### ISSUE THREAD

**Issue by abrom** [antirez/redis-doc#789]
It appears from the source that the `object` command (for now) requires 2 args being the subcommand and key.

https://github.com/antirez/redis/blob/baa98988215f005b5b57e156c68a5bdc8454a3a5/src/object.c#L1014

Would there be any objection to a PR that would update the documentation to reflect this?

At the moment it suggests that the subcommand is required but that there would be multiple optional arguments:

https://github.com/antirez/redis-doc/blob/master/commands.json#L1663

In reality the command should probably be described with `subcommand` and `key` ?

**Comment by itamarhaber** [comment]
I believe this has been addressed already - please close

**Comment by abrom** [comment]
The `HELP` subcommand invalidates this issue. Thanks
