### ISSUE TITLE
[Cluster] Mention CROSSSLOT scenario

### ISSUE THREAD

**Issue by badboy** [antirez/redis-doc#849]
Currently the Cluster spec reads:

> Commands performing complex multi-key operations like Set type unions or intersections are implemented as well as long as the keys all belong to the same node.
(from https://github.com/antirez/redis-doc/blob/master/topics/cluster-spec.md#implemented-subset)

This is slightly incorrect. All keys in a multi-key command need to belong to the same slot.
I don't know of any plans for this to change.

@antirez Am I right in my assumption? Should I change that sentence?

**Comment by jeffjo** [comment]
This confused me as well. The [code](https://github.com/antirez/redis/blob/f3980bb9fd167420acda96419d8db991cc85d1e1/src/cluster.c#L5493) enforces that keys must be hash to the same slot. I agree that the documentation should be updated.
