### ISSUE TITLE
Document running redis with docker

### ISSUE THREAD

**Issue by scriptnull** [antirez/redis-doc#857]
Redis could also be run by using its [docker image](https://hub.docker.com/r/library/redis/)

I am surprised not to see a section about running redis with docker on the official site.

Is it already present and I missed it?

or is it intentionally left out for some reason? if so, what is the reason? I am curious to know.

If it is ok to add it, I request anyone with idea about this to provide with information like the right place to add it etc. here.

Thanks.

**Comment by badboy** [comment]
The Redis project does not maintain the Docker image. That's why it is no where mentioned officially (plus Redis Cluster has issues running on Docker-like systems, so we avoid even encourage using it)

**Comment by scriptnull** [comment]
Thanks. It answers my question sufficiently. So I am closing this issue.
