### ISSUE TITLE
HGETALL Returns Issue

### ISSUE THREAD

**Issue by tkottke90** [antirez/redis-doc#874]
From working with the commands I believe there is an issue with the [HGETALL](https://redis.io/commands/hgetall) doc.  I found that the Documentation suggest that an *array* or list is returned, when an **object** is actually returned.  I found this while unit testing using mocha:

The mock data I am using is:

**Hash Key: hashTest**

Field | Value
------------ | -------------
field1 | value1
field2 | value2

The documentation suggests that the command returns an Array:

>Return value
>Array reply: list of fields and their values stored in the hash, or an empty list when key does not exist.

I was working to build a Synchronous version of the command, my understanding of an array is that the data would come through as a string array:

```
 var array = [ "field1", "value1", "field2", "value2" ] 
```

With that in mind I built my synchronous function to map those values to an object: 

```
HGETALLSync(key){
    return new Promise((resolve, reject) => {
        client.HGETALL(key, (error, result) => {
            var json = {};
            if(error){
                reject(error);
            } else {
                for(var i = 0; i < result.length; (i+2)){
                    json[result[i]] = result[i+1];
                 }
                 resolve(json);
             }
        });
    });
}
```

With this method my Unit Testing using mocha returns:

>  HGETALLSync()
>          should get all values in a hash key:
>          AssertionError: expected {} to have property 'field1'

The unit test I was running was: 

```
it('should get all fields and values in a hash', async function() {
    var hgetall_result = await spec.HGETALLSync('hashTest');
                
    expect(hgetall_result).to.includes({'field1':'value1','field2':'value2'});
});
```

I found that by removing the *for* statement and resolving the result argument rather than attempting to sort the data, I was able to get a successful test.

Updated Code: 

```
HGETALLSync(key){
    return new Promise((resolve, reject) => {
        client.HGETALL(key, (error, result) => {
            if(error){
                reject(error);
            } else {
                 resolve(result)
             }
        });
    });
}
```
I would suggest updating the documentation to reflect:

> Return value
> Object: fields as parameters and values assigned to those parameters from hash. empty object when key does not exists

**Comment by badboy** [comment]
RESP (the Redis protocol) has no notion of objects. It therefore returns a list (and the documentation is correct).
What you are seeing is a smart client that automatically turns this list into the appropriate data structure of your programming language.
