### ISSUE TITLE
Documentation bug for SET command

### ISSUE THREAD

**Issue by qrilka** [antirez/redis-doc#877]
https://redis.io/commands/set says that `SET` command has the following format:
```
SET key value [EX seconds] [PX milliseconds] [NX|XX]
```
So I try to set expiration time both in seconds and milliseconds on my Redis 3.2.1:
```
127.0.0.1:6379> set test value ex 1 px 1
(error) ERR syntax error
```
And it looks like you can't specify `EX` and `PX` option at the same time. It makes total sense but documentation says nothing about it.

**Comment by itamarhaber** [comment]
Hello @qrilka,

This looks to have been resolved - please verify and close this issue.
