### ISSUE TITLE
Sync command description?

### ISSUE THREAD

**Issue by mingrammer** [antirez/redis-doc#939]
Where is the description for [SYNC](https://redis.io/commands/sync) ?

**Comment by itamarhaber** [comment]
Hello @mingrammer 

It should be at https://github.com/antirez/redis-doc/blob/master/commands/sync.md but it is missing. Perhaps you'd like to contribute a PR to correct that?

**Comment by mingrammer** [comment]
@itamarhaber Sure. I'll send a PR for that!

**Comment by mingrammer** [comment]
I sent a PR
