### ISSUE TITLE
Add support for Streams API commands

### ISSUE THREAD

**Issue by bobby** [antirez/redis-doc#943]
It appears that the XGROUP command hasn't yet been added to command reference.

@comnik and I encountered this issue while adding support for Redis Streams to Carmine (cf. ptaoussanis/carmine#208 and ptaoussanis/carmine#210).

**Comment by bobby** [comment]
Bump, @antirez.

**Comment by bobby** [comment]
@antirez Should I open a PR to add this?  My team needs this semi-urgently in order to use Streams on our current project.

**Comment by tirkarthi** [comment]
I think he is on vacation https://github.com/antirez/redis/issues/5203 and communication will be minimal. Feel free to raise a PR.

Thanks

**Comment by bobby** [comment]
@tirkarthi observed that XACK is also missing.

**Comment by tirkarthi** [comment]
Below commands are also missing and thus they are also missing in `help @stream`. Adding them before release will help since they are used in the redis-cli

* XCLAIM
* XDEL
* XTRIM

Thanks

**Comment by bobby** [comment]
@tirkarthi @antirez I've added PR #963 to address this issue, but it needs some review.
