### ISSUE TITLE
Typo in streams intro docs

### ISSUE THREAD

**Issue by tirkarthi** [antirez/redis-doc#962]
conusmer ->  consumer . Relevant section : https://github.com/antirez/redis-doc/blob/f2590e156d329cfe801399dc194d3baedfde550b/topics/streams-intro.md#recovering-from-permanent-failures

```
XPENDING <key> <groupname> [<start-id> <end-id> <count> [<conusmer-name>]]
```

Thanks

**Comment by itamarhaber** [comment]
Thanks @tirkarthi  - this has been addressed by a merged PR so closing.
