### ISSUE TITLE
Language on https://redis.io/modules regarding licenses is wrong

### ISSUE THREAD

**Issue by wwahammy** [antirez/redis-doc#969]
If you look at the second sentence on https://redis.io/modules, it reads "Only modules under an OSI approved license are listed here." Six of the modules are NOT under an OSI approved license. While I assume you're not going to remove those from the set of modules, it would be helpful to remove that sentence so people aren't confused.

**Comment by natoscott** [comment]
@ericschultz some of the Redis Labs' modules have been forked and are being maintained as open source software once more - see: https://goodformcode.com/

**Comment by itamarhaber** [comment]
Hello @wwahammy 

This has been remedied via https://github.com/antirez/redis-io/commit/de1cb2ba2a75990e887c41f57c7ff72f1e66a9ce.

Closing, but please feel free to reopen if needed.
