### ISSUE TITLE
Cluster: nodes formatting may not agree with docs

### ISSUE THREAD

**Issue by TheKevJames** [antirez/redis-doc#983]
Running `cluster nodes` on one of my Redis clusters gives the following:
```
thekevjames@redis-node-0:~$ sudo docker exec -it redis redis-cli cluster nodes
5df14d79bcdbee400f21589d785bfd0f54fffc16 10.124.0.2:6379@16379 master - 0 1535479874968 17 connected 5461-10922
178b70b0d1bb02793d041d9194d53e5d967ee115 10.124.0.4:6379@16379 slave e40a9cfe3466d62c9ae1e35a678b73406e78ded9 0 1535479874565 22 connected
e40a9cfe3466d62c9ae1e35a678b73406e78ded9 10.124.0.5:6379@16379 myself,master - 0 1535479874000 22 connected 10923-16383
c78589cd3e0709b47e0dd79bcd7c4e353b0b8e85 10.124.0.6:6379@16379 slave 5df14d79bcdbee400f21589d785bfd0f54fffc16 0 1535479874466 17 connected
24cef8420da195a097fd6c94f3cdbd311a812e1d 10.124.0.7:6379@16379 master - 0 1535479874000 18 connected 0-5460
f42d7be5a66fae922c99a5b941494c059f3a5286 10.124.0.3:6379@16379 slave 24cef8420da195a097fd6c94f3cdbd311a812e1d 0 1535479873000 18 connected
```

More specifically, I want to point out the format of the address on each line, eg. `10.124.0.3:6379@16379` -> `ip:port@cport`. That format does not agree with the documentation [here](https://redis.io/commands/cluster-nodes) which specifies the format as `<snip> <ip:port> <snip>`.

Checking redis source code, we find [this line](https://github.com/antirez/redis/blob/e245ed9a44583c3772445e99ffa2b14407199287/src/cluster.c#L3980), which shows the `cport` should always be present.  This was originally introduced [here](https://github.com/antirez/redis/commit/1c038379f7861a6c341c1fedae5ff358f024798f) and [here](https://github.com/antirez/redis/commit/b841f3ad1a88e11a9d4abca1c7f0cf9df63e613d) which -- if I'm reading the tags right -- implies that this difference between docs and code has been present since 4.0.0.

(Moved from original issue antirez/redis#5293)

**Comment by itamarhaber** [comment]
@TheKevJames - great. Would you also submit the PR that fixes that so you can rip those sweet sweet interwebz points? :) (I'll be happy to do it on your behalf and get them all for mahself!!!)
