### ISSUE TITLE
License for this repo?

### ISSUE THREAD

**Issue by vmbrasseur** [antirez/redis-doc#985]
The footer of the website says, "This website is open source software."

Unfortunately, it does not have a license, so it's not open source, it's merely "source available."

Could someone please add a license to this repository?

Thank you!

**Comment by itamarhaber** [comment]
Hello @vmbrasseur 

The file https://github.com/antirez/redis-doc/blob/master/COPYRIGHT clearly states the type of license that the docs employ (CC-BY-SA-4). That said, I've added the plain-text version of the license under the file 'LICENSE' to make it totally findable :)
