### ISSUE TITLE
Consider adding "walrus" to Python clients?

### ISSUE THREAD

**Issue by coleifer** [antirez/redis-doc#995]
Hi, I'm the author of a project called [walrus](https://walrus.readthedocs.io/en/latest/), a Redis toolkit for Python which currently has 481 stars [on github](https://github.com/coleifer/walrus).

The library is implemented as an extension on top of `redis-py`, the recommended Python client for Redis, and has a lot of features:

* pythonic container classes
* support for zpopmin/zpopmax, bzpopmin/bzpopmax
* support for basic stream APIs (no consumer groups yet, but I'm looking into it)
* autocomplete
* cache
* full-text search
* graph store
* rate limiting
* active-record models (secondary indexes, full-text search, composable query filters, etc)
* locks

The addition to the doc would look like this:

```javascript
{
    "name": "walrus",
    "language": "Python",
    "repository": "https://github.com/coleifer/walrus",
    "description": "Lightweight Python utilities for working with Redis.",
    "authors": ["coleifer"],
    "recommended": false,
    "active": true
  },
```

I hope you'll consider adding this project to your client list.

Many thanks for Redis -- it's such a cool project.

**Comment by itamarhaber** [comment]
Helllo @coleifer - why not just make a PR to `clients.json`?

P.S. warlus is awesome, thanks for making it.

**Comment by coleifer** [comment]
I hate cluttering up my repos list with stuff. I was hoping you all might accept the json I put in the issue in lieu of a pr?

**Comment by itamarhaber** [comment]
Hate noted, in lieu if your PR I made one for you: #996 :)

Please note that I've removed the author value as it should a Twitter handle.
